<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Juan David Marin">

<title>PLS to FPS and PLSDA emulsifier type</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="PLSDAmodelforsimulatorII_files/libs/clipboard/clipboard.min.js"></script>
<script src="PLSDAmodelforsimulatorII_files/libs/quarto-html/quarto.js"></script>
<script src="PLSDAmodelforsimulatorII_files/libs/quarto-html/popper.min.js"></script>
<script src="PLSDAmodelforsimulatorII_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="PLSDAmodelforsimulatorII_files/libs/quarto-html/anchor.min.js"></script>
<link href="PLSDAmodelforsimulatorII_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="PLSDAmodelforsimulatorII_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="PLSDAmodelforsimulatorII_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="PLSDAmodelforsimulatorII_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="PLSDAmodelforsimulatorII_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">PLS to FPS and PLSDA emulsifier type</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Juan David Marin </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid" width="1440"></p>
</div>
</div>
<section id="model" class="level1">
<h1>Model</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
PLS model (class pls) summary
-------------------------------
Info: Pls model FPS
Number of selected components: 5
Cross-validation: random with 5 segments

Response variable: FPS
     X cumexpvar Y cumexpvar    R2  RMSE Slope    Bias   RPD
Cal     99.99966    99.65686 0.997 0.467 0.997  0.0000 17.11
Cv            NA          NA 0.996 0.500 0.997 -0.0101 15.99
Test    99.99979    99.61801 0.996 0.511 0.987 -0.0196 16.20</code></pre>
</div>
</div>
<section id="modificacion-de-spectros" class="level2">
<h2 class="anchored" data-anchor-id="modificacion-de-spectros">Modificacion de spectros</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
PLS model (class pls) summary
-------------------------------
Info: Pls model FPS
Number of selected components: 5
Cross-validation: none

Response variable: FPS
     X cumexpvar Y cumexpvar    R2  RMSE Slope    Bias   RPD
Cal       99.846      99.710 0.997 0.429 0.997  0.0000 18.61
Test      99.893      99.645 0.996 0.494 0.989 -0.0219 16.76</code></pre>
</div>
</div>
<p>PLS Model for FPS – Summary</p>
<p>This PLS model was built using UV spectral data to predict the sun protection factor (FPS). The model uses 5 components and includes 5-fold cross-validation to assess its performance more reliably.</p>
<p>The model explains nearly all the variation in both the predictor (X) and response (FPS) data. R² values are above 0.99 for calibration, cross-validation, and test sets, which shows strong consistency. RMSE values remain low across all sets, and the RPD values are above 16, indicating excellent predictive ability.</p>
</section>
</section>
<section id="validation" class="level1">
<h1>Validation</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Comp 1    Comp 2    Comp 3    Comp 4    Comp 5 
1.6960533 1.6840402 0.7503733 0.5389224 0.4671694 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Comp 1    Comp 2    Comp 3    Comp 4    Comp 5 
1.7096732 1.6964617 0.7724586 0.5620015 0.4997676 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Comp 1    Comp 2    Comp 3    Comp 4    Comp 5 
1.6893641 1.7071191 0.5958939 0.5074299 0.5109308 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-7-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The RMSE values tell us how far the predicted FPS values are from the true values. Lower RMSE means better prediction accuracy.</p>
<p>In calibration, RMSE decreases from 1.69 to 0.47 as more components are added.</p>
<p>In cross-validation, RMSE drops from 1.72 to 0.48, confirming the model generalizes well.</p>
<p>In the test set, RMSE starts at 1.68 and stabilizes around 0.51 after 5 components.</p>
<p>This consistent drop in RMSE across all sets shows that the model improves steadily with each added component and maintains good performance on unseen data.</p>
</section>
<section id="variance-explained-in-x-and-y" class="level1">
<h1>Variance Explained in X and Y</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      Comp 1       Comp 2       Comp 3       Comp 4       Comp 5 
89.269434411 10.663884841  0.043669215  0.013099019  0.009569748 
attr(,"name")
[1] "Variance"
attr(,"xaxis.name")
[1] "Components"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     Comp 1      Comp 2      Comp 3      Comp 4      Comp 5 
89.31399502 10.62623448  0.03720859  0.01125661  0.01109795 
attr(,"name")
[1] "Variance"
attr(,"xaxis.name")
[1] "Components"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     Comp 1      Comp 2      Comp 3      Comp 4      Comp 5 
95.47725245  0.06384216  3.57363065  0.42863273  0.11350136 
attr(,"name")
[1] "Variance"
attr(,"xaxis.name")
[1] "Components"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>      Comp 1       Comp 2       Comp 3       Comp 4       Comp 5 
95.823856036 -0.088242351  3.744789200  0.142823055 -0.005216966 
attr(,"name")
[1] "Variance"
attr(,"xaxis.name")
[1] "Components"</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="1440"></p>
</div>
</div>
<p>X (Spectral data): In both calibration and test, the first component explains about 89% of the spectral variance. The second adds around 10%, and the rest contribute very little. This means the spectral structure is mostly captured with just 2 components.</p>
<p>Y (FPS values): In calibration, component 1 alone explains over 95% of the variance in FPS. Additional components only improve the explanation slightly. In the test set, the pattern is similar: almost all variance is explained by the first component.</p>
<section id="prediction-plot" class="level2">
<h2 class="anchored" data-anchor-id="prediction-plot">Prediction plot</h2>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Comp 1    Comp 2    Comp 3    Comp 4    Comp 5 
0.9547725 0.9554109 0.9911473 0.9954336 0.9965686 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Comp 1    Comp 2    Comp 3    Comp 4    Comp 5 
0.9575716 0.9566751 0.9947210 0.9961721 0.9961191 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Comp 1    Comp 2    Comp 3    Comp 4    Comp 5 
0.9540432 0.9547507 0.9906185 0.9950341 0.9960730 </code></pre>
</div>
</div>
<p>These R² values show how well the model predicts FPS using different numbers of components. In calibration, cross-validation, and test, the R² increases from around 0.95 (1 component) to about 0.996 (5 components). The biggest improvement happens between components 2 and 3, after which the gain becomes smaller. This shows that 3 to 5 components are enough for highly accurate FPS prediction.</p>
</section>
</section>
<section id="regcoeff" class="level1">
<h1>Regcoeff</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>plotRegcoeffs(mfps, show.ci = TRUE, ncomp = 4) shows which wavelengths in the spectrum are most important to predict FPS. Peaks (high or low) mean that wavelength has a strong effect. Flat areas have little or no influence. The shaded area shows confidence; narrow bands = more reliable. This helps to understand which parts of the UV spectrum are used by the model to predict FPS.</p>
</section>
<section id="x-and-y-residuals" class="level1">
<h1>X and Y Residuals</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="1440"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     FPS octinoxate zinc_oxide eficacia_octinoxate_hplc eficacia_zno_aa
195 3.03   1.190578   1.000737                 89.87364        81.07912
241 3.37   1.036045   3.227618                 96.27422        93.47252
    spf_in_vitro emulsifier emulsifier_type base_type viscosidad    CSAT
195     8.750098    Natural           ionic     Water   778.3426 dislike
241     9.825019    Natural           ionic     Water   909.6243 dislike
    formula_price      x290      x291      x292      x293      x294      x295
195         1.406 0.5924494 0.6122781 0.5693149 0.5869363 0.5524853 0.5181107
241         2.303 0.6309757 0.6489934 0.6165801 0.6235499 0.5963763 0.5624983
         x296      x297      x298      x299      x300      x301      x302
195 0.5886221 0.5337729 0.5384237 0.5328283 0.5492268 0.5265976 0.5473201
241 0.6253067 0.5837389 0.5791523 0.5769676 0.5910754 0.5693032 0.5911735
         x303      x304      x305      x306      x307      x308      x309
195 0.5649899 0.5242019 0.5277044 0.4997457 0.5123818 0.5494149 0.4952493
241 0.6068601 0.5692311 0.5689124 0.5462481 0.5581647 0.5936570 0.5465620
         x310      x311      x312      x313      x314      x315      x316
195 0.5133346 0.4732416 0.4902859 0.5031070 0.4842781 0.4671932 0.4795806
241 0.5637884 0.5246096 0.5380585 0.5528014 0.5341217 0.5225477 0.5210810
         x317      x318      x319      x320      x321      x322      x323
195 0.4599934 0.4311052 0.4567055 0.4493295 0.4537007 0.4487055 0.4237193
241 0.5081167 0.4831647 0.5008579 0.4901868 0.4998337 0.4905349 0.4747335
         x324      x325      x326      x327      x328      x329      x330
195 0.3753761 0.3407959 0.3616554 0.3586744 0.3581217 0.3336543 0.3158565
241 0.4265902 0.3934003 0.4103148 0.4070889 0.4037060 0.3804912 0.3648886
         x331      x332      x333      x334      x335      x336      x337
195 0.3097838 0.3358360 0.3391899 0.3313731 0.3065373 0.3078544 0.2873624
241 0.3560074 0.3804804 0.3819447 0.3739135 0.3553661 0.3531489 0.3338423
         x338      x339      x340      x341      x342      x343      x344
195 0.2846226 0.2483792 0.3037807 0.2748933 0.2854124 0.3043988 0.2900788
241 0.3313718 0.2969673 0.3455087 0.3226776 0.3262324 0.3511527 0.3284319
         x345      x346      x347      x348      x349      x350      x351
195 0.2998800 0.2607584 0.3125114 0.2824057 0.2674429 0.2685923 0.3351594
241 0.3421622 0.3119527 0.3597240 0.3266833 0.3130377 0.3116366 0.3711354
         x352      x353      x354      x355      x356      x357      x358
195 0.2589331 0.2859276 0.2922338 0.2582531 0.3039019 0.2555044 0.2696217
241 0.3063347 0.3300225 0.3320816 0.3066756 0.3526884 0.3083356 0.3207033
         x359      x360      x361      x362      x363      x364      x365
195 0.2634979 0.2285840 0.2581317 0.2556634 0.2324724 0.2769146 0.2936033
241 0.3126223 0.2813435 0.3033798 0.3038998 0.2822858 0.3189359 0.3355283
         x366      x367      x368      x369      x370      x371      x372
195 0.2965908 0.2818539 0.2633728 0.3104040 0.2391278 0.2978194 0.2694675
241 0.3365101 0.3256105 0.3118436 0.3512335 0.2923306 0.3374649 0.3102170
         x373      x374      x375      x376      x377      x378      x379
195 0.3208656 0.3239431 0.2446130 0.2880715 0.2922701 0.3811324 0.3768631
241 0.3499170 0.3517622 0.2819232 0.3165646 0.3206859 0.3952412 0.3862010
         x380      x381      x382      x383      x384      x385      x386
195 0.3475005 0.3449721 0.3775443 0.3710525 0.3904895 0.3614594 0.4028349
241 0.3541284 0.3564710 0.3831475 0.3800029 0.3947652 0.3665195 0.4029992
         x387      x388      x389      x390      x391      x392      x393
195 0.3963380 0.3673284 0.3869517 0.4018234 0.3657677 0.3475067 0.3957144
241 0.4011506 0.3759055 0.3905675 0.4028927 0.3699321 0.3530555 0.3960016
         x394      x395      x396      x397      x398      x399      x400
195 0.3760360 0.3495734 0.3812618 0.4229195 0.3856767 0.3632333 0.4051418
241 0.3779585 0.3594403 0.3822265 0.4181779 0.3848631 0.3656867 0.4045479</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         x290      x291      x292      x293      x294      x295      x296
195 0.5924494 0.6122781 0.5693149 0.5869363 0.5524853 0.5181107 0.5886221
241 0.6309757 0.6489934 0.6165801 0.6235499 0.5963763 0.5624983 0.6253067
         x297      x298      x299      x300      x301      x302      x303
195 0.5337729 0.5384237 0.5328283 0.5492268 0.5265976 0.5473201 0.5649899
241 0.5837389 0.5791523 0.5769676 0.5910754 0.5693032 0.5911735 0.6068601
         x304      x305      x306      x307      x308      x309      x310
195 0.5242019 0.5277044 0.4997457 0.5123818 0.5494149 0.4952493 0.5133346
241 0.5692311 0.5689124 0.5462481 0.5581647 0.5936570 0.5465620 0.5637884
         x311      x312      x313      x314      x315      x316      x317
195 0.4732416 0.4902859 0.5031070 0.4842781 0.4671932 0.4795806 0.4599934
241 0.5246096 0.5380585 0.5528014 0.5341217 0.5225477 0.5210810 0.5081167
         x318      x319      x320      x321      x322      x323      x324
195 0.4311052 0.4567055 0.4493295 0.4537007 0.4487055 0.4237193 0.3753761
241 0.4831647 0.5008579 0.4901868 0.4998337 0.4905349 0.4747335 0.4265902
         x325      x326      x327      x328      x329      x330      x331
195 0.3407959 0.3616554 0.3586744 0.3581217 0.3336543 0.3158565 0.3097838
241 0.3934003 0.4103148 0.4070889 0.4037060 0.3804912 0.3648886 0.3560074
         x332      x333      x334      x335      x336      x337      x338
195 0.3358360 0.3391899 0.3313731 0.3065373 0.3078544 0.2873624 0.2846226
241 0.3804804 0.3819447 0.3739135 0.3553661 0.3531489 0.3338423 0.3313718
         x339      x340      x341      x342      x343      x344      x345
195 0.2483792 0.3037807 0.2748933 0.2854124 0.3043988 0.2900788 0.2998800
241 0.2969673 0.3455087 0.3226776 0.3262324 0.3511527 0.3284319 0.3421622
         x346      x347      x348      x349      x350      x351      x352
195 0.2607584 0.3125114 0.2824057 0.2674429 0.2685923 0.3351594 0.2589331
241 0.3119527 0.3597240 0.3266833 0.3130377 0.3116366 0.3711354 0.3063347
         x353      x354      x355      x356      x357      x358      x359
195 0.2859276 0.2922338 0.2582531 0.3039019 0.2555044 0.2696217 0.2634979
241 0.3300225 0.3320816 0.3066756 0.3526884 0.3083356 0.3207033 0.3126223
         x360      x361      x362      x363      x364      x365      x366
195 0.2285840 0.2581317 0.2556634 0.2324724 0.2769146 0.2936033 0.2965908
241 0.2813435 0.3033798 0.3038998 0.2822858 0.3189359 0.3355283 0.3365101
         x367      x368      x369      x370      x371      x372      x373
195 0.2818539 0.2633728 0.3104040 0.2391278 0.2978194 0.2694675 0.3208656
241 0.3256105 0.3118436 0.3512335 0.2923306 0.3374649 0.3102170 0.3499170
         x374      x375      x376      x377      x378      x379      x380
195 0.3239431 0.2446130 0.2880715 0.2922701 0.3811324 0.3768631 0.3475005
241 0.3517622 0.2819232 0.3165646 0.3206859 0.3952412 0.3862010 0.3541284
         x381      x382      x383      x384      x385      x386      x387
195 0.3449721 0.3775443 0.3710525 0.3904895 0.3614594 0.4028349 0.3963380
241 0.3564710 0.3831475 0.3800029 0.3947652 0.3665195 0.4029992 0.4011506
         x388      x389      x390      x391      x392      x393      x394
195 0.3673284 0.3869517 0.4018234 0.3657677 0.3475067 0.3957144 0.3760360
241 0.3759055 0.3905675 0.4028927 0.3699321 0.3530555 0.3960016 0.3779585
         x395      x396      x397      x398      x399      x400
195 0.3495734 0.3812618 0.4229195 0.3856767 0.3632333 0.4051418
241 0.3594403 0.3822265 0.4181779 0.3848631 0.3656867 0.4045479</code></pre>
</div>
</div>
<p>X Residuals Plot (plotXResiduals) This plot shows how well the model explains the spectral data. Most samples have low residuals, meaning the model explains their spectra well. Samples 195 and 241 are labeled as outliers, with high X-residuals. Why are 195 and 241 outliers? These two samples have the lowest FPS values. Very low concentrations of Octinoxate and Zinc Oxide Because their spectra are very different from the others (weaker UV absorbance), the model cannot explain them well using the same components. These outliers may represent edge cases in the dataset. It’s normal that the model fits less well when active ingredients are very low, since the spectral signal is weak.</p>
<p>Y Residuals Plot (plotYResiduals) This plot shows the difference between the real FPS and the predicted FPS for each sample. Most samples have small residuals, meaning the model predicts FPS very well.</p>
<p>CONCLUSIONES</p>
<p>Impact on Formulation Efficiency</p>
<p>Using this model, we need a simple UV scan and the model prediction can give you a fast, accurate estimate of FPS.</p>
<p>This improves speed during formulation development, reduces lab testing costs, and allows faster decision-making when screening new sunscreen formulations. It can also help during quality control to check that the SPF of production batches is within expected levels before running full tests. #RMSD</p>
<p>A final RMSE around 0.48–0.51 means the predicted FPS values are, on average, less than ±0.5 units away from the real FPS. This is very accurate and allows confident decision-making without the need for full lab testing. The model is reliable for both R&amp;D and production batch control.</p>
<p>Let me know if you want to visualize these RMSE trends or move on to the PLS-DA model next.</p>
</section>
<section id="variance-explained-fps-model" class="level1">
<h1>Variance Explained – FPS Model</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>The model captures both the spectral data and the target variable (FPS) very efficiently. This means the relationship between spectrum and FPS is strong and mostly linear. As a result, you can make reliable FPS predictions using minimal components, saving time and simplifying the model without losing accuracy.</p>
</section>
<section id="prediction-performance" class="level1">
<h1>Prediction Performance</h1>
<p>The model predicts FPS very well across all sets. The prediction plot confirms that observed and predicted values are very close, with minimal error. This gives confidence in using the model to estimate FPS directly from spectral data, reducing the need for in vitro SPF tests.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      FPS
179 18.55
14   5.47
195  3.03
118 20.20
229 15.50
244 17.66
299  6.27
153 12.05
90  16.75
91  23.22
256 33.85
197  7.14
291 18.53
137 19.84
26  14.06
7   29.90
287 27.44
254 18.86
211 29.20
78   8.73
81  13.45
43  13.45
143 33.21
32  19.88
109 27.94
263 34.02
23  27.91
135 30.30
224 26.74
166 25.63
217  9.15
69   9.60
72  29.85
76  21.56
63  24.05
141  6.69
210  5.64
293 15.73
41  25.07
292 28.27
223 12.83
16  28.32
116 21.97
94  26.25
6   19.53
235 30.80
200  8.82
86  25.96
253 25.30
39  29.19
159 26.06
240 24.05
209 26.06
297 29.27
50  24.38
241  3.37
34  21.22
4   20.74
13  18.43
269 14.97
127 13.84
275 20.91
52  30.97
22  28.14
89  14.53
160 20.10
25  23.43
215 17.71
35  18.13
168 27.11
112 15.39
30  25.22
140 21.23
250 29.72
121 29.66
110 16.13
158 25.97
64  23.02
142 12.41
221 18.62
199 19.50
67  26.77
151  8.08
122  9.40
79   9.52
85  31.77
165 22.88
136  5.07
51   8.67
74  27.00
178  6.92
106 22.49
98  17.48
282  6.26
249 27.51
204 28.32
174 26.02
17   9.51
190 21.27
46  10.12
54  20.72
163 22.01
225 27.48
257 22.48
216 20.21
24  21.85
113 10.30
107 29.96
273  3.50
218 16.47
154 14.54
102 23.08
255  8.83
192 27.93
155 26.26
170 22.50
5   23.85
70  22.80
259  4.26
298 28.65
277 23.22
21  22.07
55  13.95
75   6.10
164  8.43
83  22.21
251  9.92
283  8.89
284 27.43
48  29.65
77  22.88
175 33.45
111 12.14
205 29.06
1   22.99
296 29.83
289 26.89
182  8.48
88   7.08
173 27.28
20  21.08
104  7.53
93  17.73
238 31.90
108 21.50
237 11.69
42   9.25
59  29.82
84  18.28
11  15.86
226  6.15
213 19.71
201 20.63
233 10.90
276  9.96
193 18.34
185 19.11
36  13.16
222 30.47
220  9.32
125 27.93
33  18.97
40  19.86
10  16.80
228 19.91
9   20.12
285  6.65
61  24.54
266  9.92
161 18.76
286 26.48
139 19.54
57  17.63
149 25.22
29  11.10
115 14.73
172  7.59
53  22.35
131 24.20
144 21.23
145 18.86
191 10.00
234 24.78
157 22.52
130 17.29
134 26.83
247 32.12
87  16.06
261 20.89
180 17.94
152 29.09
181 20.92
128 21.48
73  22.21
105 16.41
101 20.52
274 18.09
294 27.08
290 28.40
288 28.96
271 11.94
230  5.61
58  22.85
280  7.34
126 35.23
258 28.97
27  15.89
147 28.14
206 22.00
60  20.23
95  21.67
262  4.03
198 28.47
189 32.92
31   7.84
203 25.60
260 10.61
37  18.25
156  6.59
188 20.91
232  9.10
129 28.56
66   7.88
243 31.81
207  7.02
184 28.85
114 28.81
8   24.76
264 10.49
45  26.86
18  10.39
202  5.59
252 18.46
194 22.92
133 21.80
171 24.50
272 15.73
123 15.33
71   8.87
28  11.70</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>          Comp 1      Comp 2       Comp 3       Comp 4        Comp 5
179  -109.270383 -1.84379973 -17.51569262   2.55321551 -1.1468914495
14  -1688.341353  6.43678149  53.26830295   6.94752047  2.3199027019
195 -1982.908108 20.80831496 170.23512397   8.75695457  2.3746543945
118    89.924349 -6.30850044 -42.33520553  -3.71389355 -1.8864096366
229  -477.478828 -2.75246362 -26.28384208  -1.23180859 -1.4615429992
244  -216.714815 -2.50592526 -22.08833649   2.37783391 -0.9404044032
299 -1591.762088  2.83833401  30.49969320   5.57347061  2.5951153881
153  -893.976905 -4.21890843 -32.04257600   1.13338409  1.2179397573
90   -326.573728 -7.95805700 -53.38274654 -11.12517237 -6.1846418075
91    454.511072 -5.49175598 -35.93405745  -8.26352215 -1.4191242495
256  1737.808044 12.44834783  90.70704342   3.98709498  0.5337737443
197 -1486.732139  2.17127912  10.02233341 -11.99020319 -4.3148488338
291  -111.684865 -4.20054532 -30.33913188   3.45127294 -0.2393767672
137    46.463680  0.06662705  -5.67455241   0.31431462 -2.8073257790
26   -651.321503 -4.95864978 -36.55244835   0.90196613 -0.2043177462
7    1260.947928  3.33959505  26.48950897  -4.72475217  0.7533529938
287   963.966690 -3.25205029 -19.51636427 -22.22743398 -6.2922803675
254   -71.845918 -1.71162768 -16.37769710   2.85766251 -1.0525671184
211  1176.441071  7.58129550  53.83009765   6.65476422  1.3169229249
78  -1294.780851 -1.30334745  -9.84078616   5.95089161  4.0999327600
81   -724.963192 -5.29538991 -38.01011563  -0.13547431 -0.5639894687
43   -724.963192 -5.17168891 -37.37017102   0.17409133 -0.3671488896
143  1660.544633 12.30164653  89.10744666   5.47849450  0.6480110107
32     51.292644 -0.17521910  -6.80699519   1.28745942 -2.2343209501
109  1024.328730  2.39666326  18.88558171   1.40756264  2.2060610159
263  1758.331138 12.05757085  88.24978866   2.62251326  0.5303001259
23   1020.707008  7.32171484  50.39653314   6.43506733  0.2230576145
135  1309.237560  4.17386875  32.37469073  -3.72424600  0.9578396311
224   879.459834 -2.95452488 -17.67970559 -14.71522632 -2.9449717003
166   745.456105 -2.16460390 -12.80798590  -4.07486255  0.8480921071
217 -1244.076737 -1.86417344 -14.12977072   5.37525865  3.9314253054
69  -1189.750901 -1.94686018 -17.90703944   2.84403806  3.8114070886
72   1254.911724  5.85255933  43.26929876   3.18592289  2.0014173568
76    254.109098 -5.31406580 -35.41185585  -2.22954482 -0.3946166950
63    554.712058  1.45472915   9.06480611   6.24986983  1.3971829168
141 -1541.057975  2.50789542  22.07094069   7.60535480  3.5341387831
210 -1667.818259  5.95583148  47.66711871   3.61255150  0.9596411027
293  -449.712289 -5.19513115 -37.54995380   1.23582631 -0.8405938246
41    677.850620  4.52611301  28.87315689   4.82100995 -0.6931525226
292  1064.167677  2.61057994  20.55417522   0.77394718  2.1058553183
223  -799.812122 -2.25286450 -28.48740655 -12.10024557 -4.0243774691
16   1070.203881  7.78609962  53.89497278   6.57124476  0.2741820594
116   303.605971 -0.87528835  -7.51338323   5.65489856  1.0476594514
94    820.305035  1.41283958  11.11037385   4.12204429  2.4910993184
6       9.039216 -0.57203605  -9.45945807   1.51220987 -2.0181951718
235  1369.599600  7.72207235  56.48211981   4.10279821  1.7277064230
200 -1283.915684 -0.66073046 -11.48269726  -1.76403381  2.1146333089
86    785.295051 -2.24606823 -13.19726646  -6.06988843  0.2716697168
253   705.617158  0.79604968   6.30559758   4.93696115  2.4059001764
39   1175.233831  2.69095035  21.68415466  -3.24499883  1.1937518866
159   797.367459  3.58491413  24.69942038   6.50254529  1.6221802679
240   554.712058  1.38367384   8.61139784   6.19760091  1.4100604746
209   797.367459  5.36172548  35.52538560   5.64103444 -0.1630312272
297  1184.891757  6.21798588  45.13356868   5.31696312  2.0006477927
50    594.551005  3.02289888  18.91189507   5.62331373  0.2571315911
241 -1941.861921 17.90433936 146.34622850  -0.77317118 -4.9728617715
34    213.062911  0.23633302  -2.17427607   3.90083373 -0.7584849902
4     155.115353 -6.77375257 -45.13712280  -7.03611828 -2.7099877375
13   -123.757273 -5.72642205 -39.42572725   0.14053999 -1.4152844067
269  -541.462590 -2.74572414 -26.93348228  -2.31445924 -1.5412897925
127  -677.880801 -2.25172017 -27.38809402  -9.88752731 -4.0668126983
275   175.638446 -3.34525528 -23.40781394   4.02339221  0.8625472564
52   1390.122693 10.79020745  76.62000134   7.08659435  0.4688387117
22   1048.473546  3.02429249  23.18543758   2.30720299  2.2854109011
89   -594.581186 -3.35708355 -29.55462698  -0.17174176 -0.3317412030
160    77.851941  0.09485305  -5.00808437   1.11675604 -2.3870485167
25    479.863128 -5.74413696 -37.55548785 -10.50506828 -2.1576264964
215  -210.678611 -5.51191145 -38.45015823   0.92043411 -1.2567238046
35   -159.974497 -5.47734716 -38.07372475   0.96390029 -1.1835076454
168   924.127744 -2.18593037 -12.32097370 -12.98739074 -2.1732519499
112  -490.758477 -5.69160024 -40.27526975  -0.06921574 -1.3757392831
30    695.959232  4.56008118  29.35088161   5.13819081 -0.4486494272
140   214.270152 -3.07641350 -21.53545613   4.17641426  1.0280191071
250  1239.217593  8.65751656  61.36074014   6.86456226  0.9985444431
121  1231.974148  4.83612034  36.37317743   1.44580364  1.9552177678
110  -401.422657 -7.75501724 -52.15343800  -9.87209592 -5.7223696596
158   786.502292 -4.48932796 -28.36308954 -18.40432292 -4.6891199766
64    430.366256 -4.26224733 -27.91427935  -2.13257379  0.5277744446
142  -850.516236 -4.61132423 -34.04747221   0.74060915  0.6081281700
221  -100.819698 -2.86625376 -22.78801118   3.99428840 -0.2576244119
199     5.417493 -4.27537168 -30.08915677   3.21826076 -0.0006328757
67    883.081556  2.66325988  19.64741061   5.08412605  2.4114926211
151 -1373.251503 -1.60347720  -4.84049687   3.16004311  1.2845653134
122 -1213.895717 -2.75823071 -18.04952258   4.30358138  2.5847065304
79  -1199.408828 -1.28918887 -18.17794710  -4.46921239  1.5079342263
85   1486.701958  8.99572972  65.80196662   3.68092241  1.4066165922
165   413.464884  0.23115275   0.20824715   5.96837476  1.1831862269
136 -1736.630985  7.74126934  66.91379063  10.09358248  3.8990326521
51  -1302.024296 -0.54727108  -9.64044670  -0.23028075  2.5844993324
74    910.848095  4.85777076  33.84819853   6.64728936  1.5306082133
178 -1513.291436  0.90786920  15.40975205   4.17972860  1.8775913021
106   366.382493 -6.33668479 -41.76588129  -9.82578239 -2.4438842681
98   -238.445149 -4.88294440 -34.96930403   2.30434764 -0.7283037503
282 -1592.969329  4.26340289  28.85840604 -11.97280932 -5.7935562997
249   972.417376  3.19932444  23.80250933   4.41666983  2.4128856984
204  1070.203881 -1.25776199  -5.55306938 -17.03229179 -3.8118901110
174   792.538496 -1.31147831  -6.92586578  -2.53829277  1.3557134513
17  -1200.616068 -1.69604067 -16.92661759   2.17001888  3.7232573382
190   219.099115 -6.13790794 -40.85986966  -5.05234145 -1.5675464312
46  -1126.974379 -3.89659371 -25.68139761   0.88388475  0.7489502656
54    152.700871 -5.31643865 -35.79797000  -0.63721326 -0.4610716455
163   308.434934 -1.49885842 -11.18345785   5.49343154  1.3687482584
225   968.795653 -0.74843227  -2.41365612  -7.96683584 -0.2026223246
257   365.175252 -5.11525016 -33.73389163  -3.85686025 -0.3180936768
216    91.131590 -2.21146285 -17.31265976   5.00414785  0.4057148939
24    289.119082 -5.17145764 -34.36568315  -2.35940857 -0.2400646040
113 -1105.244045 -1.58520419 -24.51086898 -13.28293622 -2.1095485879
107  1268.191372  7.37134403  53.34874168   5.50480539  1.7620833650
273 -1926.167791 16.97468414 138.69064994  -1.06951924 -5.0943209260
218  -360.376470 -1.82880341 -21.17066244  -3.52451888 -3.2906561654
154  -593.373945 -3.44016484 -29.90224181   0.04854050 -0.2671487745
102   437.609700 -3.53630890 -23.17505860   0.17456983  1.1814461588
255 -1282.708443 -2.84060153 -14.91419362   2.02830356  0.7782877411
192  1023.121489  7.80419161  53.40013739   6.15909346 -0.2647985573
155   821.512275  5.74766675  38.15907057   5.50463376 -0.3665777957
170   367.589734 -0.44509361  -4.29879675   5.87045288  1.2797407128
5     530.567242 -3.60335810 -23.21608419  -2.39395952  0.8211832743
70    403.806958  0.53716274   1.90420734   5.78330603  0.8414698218
259 -1834.417490 12.06074982  98.41500004   3.19614860 -1.3341001901
298  1110.042827  4.32205046  32.15254962   3.60923521  2.2768598605
277   454.511072  0.45919058   1.98032363   6.01846816  1.3038542494
21    315.678379 -6.90460127 -45.63560077 -11.55738241 -3.4136654438
55   -664.601152 -6.80363425 -46.10509462  -6.22052362 -3.8761035628
75  -1612.285182  4.67742100  32.75602220 -11.01285139 -5.5864780330
164 -1330.998075 -0.01554783  -8.22642485  -6.94006807 -0.3832718246
83    332.579751 -0.24944967  -3.49052480   5.73839004  0.9011087334
251 -1151.119196 -2.12376504 -20.25697192   1.49909569  3.5092974966
283 -1275.464998 -0.75646979 -12.07632251  -1.36332106  2.3164660711
284   962.759449  3.78241396  27.49313583   5.42333157  2.2775485288
48   1230.766907  2.62865358  21.52283092  -6.22872331  0.3399277092
77    413.464884  1.65956003   8.55948959   4.82841799 -0.2375015986
175  1689.518412 13.69429307  98.53279053   6.72164310  0.1886125232
111  -883.111737 -6.30481130 -41.74425293  -7.48053299 -3.9854478893
205  1159.539700  8.26014828  57.95890565   6.90370772  0.7318983323
1     426.744533 -6.35509267 -41.76446563 -11.94756797 -2.9625349671
296  1252.497242  4.25770688  32.63073238  -0.97189481  1.5914002272
289   897.568446  5.16484600  35.59423390   6.59195180  1.1408924005
182 -1324.961871 -0.44059725  -7.19907186   2.13240932  3.2702716841
88  -1493.975583  2.24208034  11.86971951  -7.54831130 -2.2235450425
173   944.650837  0.65850019   6.91496043  -1.15345635  1.7899637284
20    196.161540 -2.56943793 -18.56236153   4.89404276  0.9970910472
104 -1439.649747  0.22647712   6.11105243   7.59937779  3.4989058547
93   -208.264129 -1.25265304 -16.24288786  -1.94232017 -3.2679830540
238  1502.396088  7.74630066  57.55944887   0.18156983  1.2511104234
108   246.865654 -2.45949222 -17.51910265   4.82941859  1.2120080897
237  -937.437574 -5.51745114 -37.04308782  -3.72129704 -1.9678658614
42  -1232.004329 -0.86460529 -16.87161205  -9.37597114 -0.7832009878
59   1251.290001  6.09440035  44.85493130   3.80517563  2.0389003862
84   -141.865885 -1.88365583 -18.11496699   2.13163811 -1.2994762634
11   -434.018159 -3.93098126 -31.02926503   2.13765658 -0.3015617372
226 -1606.248978  3.83249898  34.41777225   8.65366581  3.4952792753
213    30.769550 -0.19093698  -7.21824382   0.78862918 -2.4923729562
201   141.835704 -5.68285487 -38.18271508  -1.81877749 -0.9161392507
233 -1032.809597 -2.64026964 -25.46947950  -0.93884287  2.3189626178
276 -1146.290232 -1.44754277 -22.07441992  -9.95230825 -0.6079948311
193  -134.622440 -1.13870121 -14.50531806  -0.28247588 -2.6550236364
185   -41.664898 -7.52019864 -50.34974010  -8.77452822 -4.5286737768
36   -759.973176 -5.08254280 -36.83380187   0.19804741 -0.1953450696
222  1329.760653  4.40706137  34.04459957  -3.80671414  0.8961707178
220 -1223.553644 -1.93405323 -15.79289548   4.56727810  3.9437317795
125  1023.121489  0.92854240   9.10576943  -3.28960334  1.2630542965
33    -58.566269 -2.77560765 -21.87926440   4.28543200 -0.1078773031
40     48.878162 -5.73982310 -38.86010286  -0.96129400 -1.1335215232
10   -320.537524 -6.52324672 -44.71889238  -2.61606547 -2.7322974830
228    54.914366 -5.34354271 -36.38103923   0.32959168 -0.6727108475
9      80.266423 -2.51204863 -19.14975372   4.92584144  0.4443583979
285 -1545.886938  3.15060826  21.11195032  -3.62235115 -0.9734706877
61    613.866857  0.73505248   5.18188035   5.79892074  2.1257628715
266 -1151.119196 -2.26787876 -20.19501502   2.49683178  3.6509323537
161   -83.918326 -4.10387345 -29.61842832   3.57607799 -0.1581359324
286   848.071573  4.03875037  28.04802180   6.50587163  1.6361922897
139    10.246456 -2.35093871 -18.89613561   4.53884099 -0.0011657872
57   -220.336537 -7.06246140 -47.79386629  -5.24741642 -3.7045655473
149   695.959232  0.86670812   6.67478652   5.14355133  2.3608290935
29  -1008.664781 -5.60302906 -36.27083045  -6.31351042 -3.1957813728
115  -570.436370 -5.36592848 -38.64860475   0.44697059 -0.8444823902
172 -1432.406302  1.09402747   4.41163407  -0.51619906  1.5287719010
53    349.481122 -2.50510364 -17.08928231   4.03368008  1.5794495638
131   572.820670 -2.98071873 -18.93834369  -1.36425734  1.2427557610
144   214.270152 -4.71279459 -31.74053269   0.49917207  0.2119251402
145   -71.845918 -7.78344759 -52.08159380 -10.26561407 -5.2487631787
191 -1141.461269 -2.04032833 -20.78138172   0.18634419  3.1943227146
234   642.840637 -4.84354252 -31.10434862 -12.57598789 -2.4438734976
157   370.004215 -6.61715970 -43.62684007 -11.51938222 -3.0842378416
130  -261.382724 -5.03433177 -35.91115637   2.00816832 -0.8338018255
134   890.325001 -0.70090077  -2.42471742  -4.03806710  1.0142164045
247  1528.955386  8.68413534  64.02106143   1.76692279  1.2703671772
87   -409.873343 -4.65846195 -34.55337085   2.13402203 -0.4908453542
261   173.223965 -1.32741847 -11.46095623   5.16640777  0.4143025241
180  -182.912072 -6.38568279 -43.58975251  -2.10301887 -2.3992349135
152  1163.161423  7.78982717  55.02442962   6.82012648  1.1151436263
181   176.845687 -6.67057774 -44.43015150  -6.85909102 -2.5022132765
128   244.451172 -3.24662291 -22.38243498   3.69153000  1.1014767031
73    332.579751 -4.60956292 -30.57110554  -1.16519834  0.3514744731
105  -367.619915 -1.94605202 -21.74601843  -3.05966320 -3.0092420393
101   128.556055 -3.35383238 -23.78089863   4.21412672  0.6794595657
274  -164.803460 -0.98078933 -14.31830958  -1.95620090 -3.4640133676
294   920.506021 -2.38130042 -13.66233387 -13.88376074 -2.5513849479
290  1079.861807  0.36016955   5.50815466  -8.60028554 -0.3989817647
288  1147.467292  4.24273638  31.89759714   2.50392716  2.2023051989
271  -907.256553 -3.98356788 -31.00534194   1.23657408  1.5162048991
230 -1671.439981  6.06363075  48.43610751   3.26141813  0.7538574765
58    409.843162 -5.66393468 -37.20379091  -7.64935204 -1.4049291846
280 -1462.587323  1.77079959   5.52618248 -15.71200995 -5.8940386211
126  1904.407275 15.28042969 110.95124712   5.09612622 -0.1669371190
258  1148.674533  4.45150646  33.27451938   2.92415929  2.2005054065
27   -430.396437 -5.41809805 -38.67673864   0.83439775 -1.0931756068
147  1048.473546  7.06238650  49.15497117   6.76286421  0.8122516071
206   307.227694 -1.99468155 -14.24153998   5.02991261  1.4235517590
60     93.546072 -4.40639178 -30.38482631   2.54275070  0.1831807126
95    267.388747 -4.55084346 -30.46629703   0.21067500  0.4132346801
262 -1862.184028 13.14562788 110.25711155  11.90972768  5.2235190290
198  1088.312493  7.85470747  54.56438904   6.71593034  0.4346223652
189  1625.534650 11.43940308  83.10296546   4.83552135  0.8543112511
31  -1402.225282  0.59103791   0.76891267   0.80931171  2.2929493919
203   741.834383  4.41084111  29.09313040   5.94524040  0.3342254687
260 -1067.819580 -4.08615408 -28.12252295   0.76554222  0.9068684556
37   -145.487607 -4.97372130 -35.04284633   2.16195613 -0.7226352319
156 -1553.130383  2.36246582  24.14400327   8.14266905  3.3315682872
188   175.638446 -4.81646083 -32.55621409   0.68837841  0.0655432522
232 -1250.112941 -0.69495283 -16.53735302 -12.67759503 -2.4334133851
129  1099.177660  5.43348264  39.31008443   5.58772449  2.0768664365
66  -1397.396319  0.65812464  -0.04690057  -1.82289044  1.2868302401
243  1491.530921  7.35454319  54.85187614  -0.58146264  1.1879959124
207 -1501.219028  1.67531859  15.39566966   7.55422450  3.7029795870
184  1134.187643  5.96412047  43.05235600   5.75415885  1.9880558908
114  1129.358680  5.25304199  38.38732595   4.84855168  2.1647201408
8     640.426155  0.64840028   4.84665005   5.46897199  2.2357001886
264 -1082.306470 -2.67222377 -23.64440475   1.42516359  3.1255936842
45    893.946724 -0.63450011  -1.95467014  -3.92077225  1.0593986002
18  -1094.378878 -1.64829343 -25.03909472 -13.46029839 -2.2244987957
202 -1673.854463  5.96817617  50.01444345   7.80669787  2.8239930870
252  -120.135550 -6.71260993 -45.42157892  -3.79869101 -2.8946632050
194   418.293848 -4.27409423 -28.05706362  -1.87352914  0.5428461149
133   283.082878 -4.52921346 -30.24769274   0.02215242  0.4465798064
171   609.037894 -2.96136780 -18.64744560  -2.37946311  1.0680242521
272  -449.712289 -5.81674545 -40.89426315  -0.29771175 -1.5853903908
123  -498.001921 -2.10486013 -24.37794153  -5.91380595 -3.5672559527
71  -1277.879480 -0.50014027 -13.53737345  -9.33399889 -1.0696470625
28   -936.230333 -2.34114553 -27.94119122  -8.99735209 -1.3717400210
attr(,"yaxis.name")
[1] "Objects"
attr(,"name")
[1] "Y-scores"
attr(,"xaxis.name")
[1] "Components"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
Results of data decomposition (class ldecomp).

Major fields:
$scores - matrix with score values
$T2 - matrix with T2 distances
$Q - matrix with Q residuals
$ncomp.selected - selected number of components
$expvar - explained variance for each component
$cumexpvar - cumulative explained variance</code></pre>
</div>
</div>
<section id="section" class="level24">
<p class="heading"></p>
<p>PLS-DA</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
PLS-DA model (class plsda)

Call:
selectCompNum.pls(obj = model, selcrit = ncomp.selcrit)

Major fields:
$ncomp - number of calculated components
$ncomp.selected - number of selected components
$coeffs - vector with regression coefficients
$xloadings - vector with x loadings
$yloadings - vector with Y loadings
$weights - vector with weights
$calres - results for calibration set

Try summary(model) and plot(model) to see the model performance.</code></pre>
</div>
</div>
</section>
</section>
<section id="model-pls-da" class="level1">
<h1>Model PLS-DA</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
PLS-DA model (class plsda) summary
------------------------------------
Info: Modelo PLS-DA para clasificación binaria UV 290-400nm
Number of selected components: 7
Cross-validation: venetian blinds with 10 segments

Class #1 (Natural)
    X cumexpvar Y cumexpvar  TP FP TN FN Spec. Sens. Accuracy
Cal         100       66.62 130 14 90  6 0.865 0.956    0.917
Cv           NA          NA 130 16 88  6 0.846 0.956    0.908

Class #2 (Sintetic)
    X cumexpvar Y cumexpvar TP FP  TN FN Spec. Sens. Accuracy
Cal         100       66.62 90  6 130 14 0.956 0.865    0.917
Cv           NA          NA 88  6 130 16 0.956 0.846    0.908</code></pre>
</div>
</div>
<p>Using PLS-DA to Classify Emulsifiers from UV Spectra</p>
<p>In this part of the project, we wanted to know if it’s possible to identify the type of emulsifier used in a sunscreen formulation — Natural or Synthetic — using only its UV spectrum.</p>
<p>We built a PLS-DA model using spectral data between 290–400 nm, and we trained it on 80% of the samples. The model used 7 components and was validated using 10-fold cross-validation to make sure it works well on new data.</p>
<p>The results were very encouraging.</p>
<p>The model achieved over 90% accuracy in both training and cross-validation. It was able to correctly identify most of the Natural and Synthetic samples. Specifically:</p>
<p>For Natural emulsifiers, the model had 95.6% sensitivity — meaning it detected almost all Natural samples.</p>
<p>For Synthetic, it had 95.6% specificity — meaning it rarely confused a Synthetic sample as Natural.</p>
<p>This tells us that the UV spectrum contains enough chemical or physical information to detect differences between emulsifier types — maybe due to scattering, base behavior, or how actives are dispersed.</p>
<p>But more importantly, this model has real practical value:</p>
<p>In formulation, it gives us a quick way to confirm that the correct emulsifier was used — no need to manually check the recipe or wait for lab tests.</p>
<p>In quality control, it can help detect possible errors early, just by scanning the product.</p>
<p>And in cost and time savings, it avoids extra lab work and speeds up decisions in both R&amp;D and production.</p>
<p>In short, the model doesn’t just classify — it helps ensure the right ingredients are used, faster and with more confidence.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid" width="1440"></p>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Natural"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Comp 1    Comp 2    Comp 3    Comp 4    Comp 5    Comp 6    Comp 7 
0.8897059 0.8970588 0.9411765 0.9852941 0.9779412 0.9632353 0.9558824 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Sintetic"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Comp 1    Comp 2    Comp 3    Comp 4    Comp 5    Comp 6    Comp 7 
0.9519231 0.8942308 0.8653846 0.8557692 0.8653846 0.8653846 0.8653846 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Total"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>   Comp 1    Comp 2    Comp 3    Comp 4    Comp 5    Comp 6    Comp 7 
0.9166667 0.8958333 0.9083333 0.9291667 0.9291667 0.9208333 0.9166667 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "------------"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            Comp 1    Comp 2    Comp 3    Comp 4    Comp 5    Comp 6    Comp 7
Natural  0.8897059 0.8970588 0.9411765 0.9852941 0.9779412 0.9632353 0.9558824
Sintetic 0.9519231 0.8942308 0.8653846 0.8557692 0.8653846 0.8653846 0.8653846
Total    0.9166667 0.8958333 0.9083333 0.9291667 0.9291667 0.9208333 0.9166667</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>               [,1]      [,2]       [,3]       [,4]       [,5]       [,6]
Natural  0.08333333 0.1041667 0.09166667 0.07083333 0.07083333 0.07916667
Sintetic 0.08333333 0.1041667 0.09166667 0.07083333 0.07083333 0.07916667
Total    0.08333333 0.1041667 0.09166667 0.07083333 0.07083333 0.07916667
               [,7]
Natural  0.08333333
Sintetic 0.08333333
Total    0.08333333</code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>            Comp 1    Comp 2    Comp 3    Comp 4    Comp 5    Comp 6    Comp 7
Natural  0.8897059 0.8970588 0.9411765 0.9852941 0.9779412 0.9632353 0.9558824
Sintetic 0.9519231 0.8942308 0.8653846 0.8557692 0.8653846 0.8653846 0.8653846
Total    0.9166667 0.8958333 0.9083333 0.9291667 0.9291667 0.9208333 0.9166667</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            Comp 1    Comp 2    Comp 3    Comp 4    Comp 5    Comp 6    Comp 7
Natural  0.8455882 0.8455882 0.9338235 0.9779412 0.9705882 0.9558824 0.9558824
Sintetic 0.9423077 0.9038462 0.8653846 0.8365385 0.8653846 0.8461538 0.8461538
Total    0.8875000 0.8708333 0.9041667 0.9166667 0.9250000 0.9083333 0.9083333</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            Comp 1    Comp 2    Comp 3    Comp 4    Comp 5    Comp 6    Comp 7
Natural  0.8897059 0.8970588 0.9411765 0.9852941 0.9779412 0.9632353 0.9558824
Sintetic 0.9519231 0.8942308 0.8653846 0.8557692 0.8653846 0.8653846 0.8653846
Total    0.9166667 0.8958333 0.9083333 0.9291667 0.9291667 0.9208333 0.9166667</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>            Comp 1    Comp 2    Comp 3    Comp 4    Comp 5    Comp 6    Comp 7
Natural  0.8455882 0.8455882 0.9338235 0.9779412 0.9705882 0.9558824 0.9558824
Sintetic 0.9423077 0.9038462 0.8653846 0.8365385 0.8653846 0.8461538 0.8461538
Total    0.8875000 0.8708333 0.9041667 0.9166667 0.9250000 0.9083333 0.9083333</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>               [,1]      [,2]       [,3]       [,4]       [,5]       [,6]
Natural  0.08333333 0.1041667 0.09166667 0.07083333 0.07083333 0.07916667
Sintetic 0.08333333 0.1041667 0.09166667 0.07083333 0.07083333 0.07916667
Total    0.08333333 0.1041667 0.09166667 0.07083333 0.07083333 0.07916667
               [,7]
Natural  0.08333333
Sintetic 0.08333333
Total    0.08333333</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>           [,1]      [,2]       [,3]       [,4]  [,5]       [,6]       [,7]
Natural  0.1125 0.1291667 0.09583333 0.08333333 0.075 0.09166667 0.09166667
Sintetic 0.1125 0.1291667 0.09583333 0.08333333 0.075 0.09166667 0.09166667
Total    0.1125 0.1291667 0.09583333 0.08333333 0.075 0.09166667 0.09166667</code></pre>
</div>
</div>
<p>How well does the model classify emulsifiers?</p>
<p>We wanted to know how many emulsifier samples the model could classify correctly at each number of components. We focused on two things: sensitivity (how many real samples were detected) and misclassification rate (how many were wrong). As the number of components increases from 1 to 4, the model becomes more stable: In cross-validation, the best balance is reached at 4 or 5 components. At this point, the model identifies almost all Natural samples (97–98% sensitivity) and keeps a good balance for Synthetic (around 86%). The total misclassification rate drops to around 7.5%, which is very low. This means the model is reliable in telling what emulsifier type was used, even before checking the formulation manually.</p>
</section>
<section id="visualizar-resultados-de-clasificación-con-ncomp_optimo" class="level1">
<h1>Visualizar Resultados de Clasificación (con ncomp_optimo)</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="obtener-la-matriz-de-confusión" class="level1">
<h1>Obtener la Matriz de Confusión</h1>
<p>Esto resume numéricamente el rendimiento de la clasificación.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>         Natural Sintetic None
Natural      130        6    0
Sintetic      16       88    0</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Natural Sintetic None
Natural      130        6    0
Sintetic      14       90    0</code></pre>
</div>
</div>
<p>After training the PLS-DA model, we checked how many samples were classified correctly and how many were confused. The confusion matrix gives us that picture. In both calibration and cross-validation, the model shows a very clear pattern: It correctly classified 130 out of 136 Natural samples. It correctly classified 88 to 90 out of 104 Synthetic samples. Only a small number of samples were confused between classes. So, the model is more accurate for Natural emulsifiers, but still performs very well for Synthetic ones.</p>
</section>
<section id="analizar-la-importancia-de-las-variables-longitudes-de-onda" class="level1">
<h1>Analizar la Importancia de las Variables (Longitudes de Onda)</h1>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="1440"></p>
</div>
</div>
<p>What wavelengths are important to classify emulsifiers?</p>
<p>We used two tools to understand which parts of the UV spectrum help the model separate Natural from Synthetic emulsifiers:</p>
<p>Regression Coefficient Plot (plotRegcoeffs) This plot shows which wavelengths contribute the most to the classification.</p>
<p>If the value is high or low, that wavelength has a strong influence.</p>
<p>If it is close to zero, it means that wavelength is not useful for separating the classes.</p>
<p>VIP Scores (plotVIPScores) This plot tells us the importance of each wavelength in the model.</p>
<p>Wavelengths with VIP &gt; 1 are the most important.</p>
<p>These are the zones where Natural and Synthetic samples show the biggest spectral differences.</p>
</section>
<section id="predictions" class="level1">
<h1>Predictions</h1>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  2   3  12  15  19  38  44  47  49  56  62  65  68  80  82  92  96  97  99 100 
 -1  -1   1  -1   1   1  -1  -1   1  -1  -1  -1  -1  -1   1   1  -1  -1  -1   1 
103 117 119 120 124 132 138 146 148 150 162 167 169 176 177 183 186 187 196 208 
 -1  -1  -1   1   1  -1  -1   1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1   1  -1 
212 214 219 227 231 236 239 242 245 246 248 265 267 268 270 278 279 281 295 300 
  1  -1   1  -1  -1  -1   1  -1  -1   1  -1   1  -1  -1   1  -1   1   1  -1  -1 </code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
PLS-DA results (class plsdares) summary:
Number of selected components: 7

Class #1 (Natural):
       X expvar X cumexpvar Y expvar Y cumexpvar TP FP TN FN Spec. Sens.
Comp 1   60.431      60.431   49.608      49.608 27  3 26  4 0.897 0.871
Comp 2   22.367      82.798    0.469      50.076 27  6 23  4 0.793 0.871
Comp 3   16.960      99.759    5.640      55.717 30 10 19  1 0.655 0.968
Comp 4    0.097      99.856    2.763      58.480 30 11 18  1 0.621 0.968
Comp 5    0.137      99.993    0.581      59.061 30  8 21  1 0.724 0.968
Comp 6    0.006      99.999    2.828      61.889 30 10 19  1 0.655 0.968
Comp 7    0.001     100.000   -0.809      61.080 30 11 18  1 0.621 0.968
       Accuracy
Comp 1    0.883
Comp 2    0.833
Comp 3    0.817
Comp 4    0.800
Comp 5    0.850
Comp 6    0.817
Comp 7    0.800


Class #2 (Sintetic):
       X expvar X cumexpvar Y expvar Y cumexpvar TP FP TN FN Spec. Sens.
Comp 1   60.431      60.431   49.608      49.608 26  4 27  3 0.871 0.897
Comp 2   22.367      82.798    0.469      50.076 23  4 27  6 0.871 0.793
Comp 3   16.960      99.759    5.640      55.717 19  1 30 10 0.968 0.655
Comp 4    0.097      99.856    2.763      58.480 18  1 30 11 0.968 0.621
Comp 5    0.137      99.993    0.581      59.061 21  1 30  8 0.968 0.724
Comp 6    0.006      99.999    2.828      61.889 19  1 30 10 0.968 0.655
Comp 7    0.001     100.000   -0.809      61.080 18  1 30 11 0.968 0.621
       Accuracy
Comp 1    0.883
Comp 2    0.833
Comp 3    0.817
Comp 4    0.800
Comp 5    0.850
Comp 6    0.817
Comp 7    0.800</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>         Natural Sintetic None
Natural       30        1    0
Sintetic      11       18    0</code></pre>
</div>
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>What really happened in the test predictions</p>
<p>We tested the PLS-DA model on new samples to classify them as Natural or Synthetic based on their UV spectra. The overall accuracy was 88%, which seems strong at first.</p>
<p>But when we look closer:</p>
<p>The model was very good at predicting Natural (30 out of 31 correct).</p>
<p>But it struggled with Synthetic, correctly predicting only 18 out of 29.</p>
<p>That means more than one-third of the Synthetic samples were misclassified as Natural.</p>
<section id="section-1" class="level17">
<p class="heading"></p>
<p>Conclusion:</p>
<p>This PLS-DA model shows that UV spectral data can be used to classify emulsifier types in sunscreen formulations. While the model performs very well for identifying Natural emulsifiers, its performance is lower for Synthetic. Even so, the results are promising.</p>
<p>Although it’s not perfect for final classification decisions, the model is a useful tool for fast screening and early checks during formulation and production. It allows:</p>
<p>Quick detection of possible formulation errors,</p>
<p>Confirmation of ingredient type without lab testing,</p>
<p>Faster and cheaper quality control,</p>
<p>And better data tracking during development.</p>
<p>With further improvement — such as better class balance, fewer components, or selected wavelengths — this model can become a reliable and cost-effective method to support formulation optimization and reduce lab workload.</p>
<p>In short, the model is a solid first step toward building a faster, more automated, and resource-efficient process for formulation control.</p>
<p>Moreover, we can go farther by using analysis automation tools in order to gain more efficiency in the process. Let’s take a look at the next steps.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="PLSDAmodelforsimulatorII_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>